config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  # get 'index', to: 'tasks#index'

  # get 'show', to: 'tasks#show'

  # get 'new', to: 'tasks#new'

  # # get 'create', to: 'tasks#create'

  # get 'edit', to: 'tasks#edit'

  # # get 'update', to: 'tasks#update'

  # # get 'destroy', to: 'tasks#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
     @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    Task.create(task_params)

    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)

    redirect_to tasks_path
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

    def task_params
      params.require(:task).permit(:name, :description, :done)
    end

    def set_task
      @task = Task.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<!-- <p>Find me in app/views/tasks/index.html.erb</p> -->
<%= link_to 'New task', new_task_path  %>
<% @tasks.each do |task| %>
  <h2><%= task.name %></h2>
  <!-- <p><%= task.description %></p> -->
<% end %>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<h2><%= @task.name %></h2>
<p><%= @task.description %></p>

<%= link_to "Delete", task_path(@task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>